//===- TTXTypes.td --------------------------------------------------------===//
//
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause.
// For more license information:
//   https://github.com/qualcomm/hexagon-mlir/LICENSE.txt
//
//===----------------------------------------------------------------------===//

#ifndef HEXAGON_DIALECT_TTX_IR_TTX_TYPES_TD
#define HEXAGON_DIALECT_TTX_IR_TTX_TYPES_TD

include "mlir/IR/AttrTypeBase.td"
include "mlir/IR/EnumAttr.td"
include "mlir/IR/BuiltinTypeInterfaces.td"
include "hexagon/Dialect/TTX/IR/TTXDialect.td"


#endif // HEXAGON_DIALECT_TTX_IR_TTX_TYPES_TD
